version: '3'
services:
  client: 
    build: ./client
    command: npm run start
    ports: 
      - 3000:3000
  server:
    build: npm run start
    command: npm run start
    ports: 
      - 5000:5000