name: Docker build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubunu-latest

  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-docker-action@v2
      with:
        version: latest

    - name: Build and run app with Docker Compose
      run: |
        docker-compose build
        docker-compose up
